<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
  <h2 class="text-danger">TODO: fix browse controls for BS 4.0.1</h2>
  <div class="row">
    <div class="col-md-3 col-sm-12">
      <?php echo $this->pagination(); ?>
    </div>
    <div class="col-md-3 col-sm-12">
      <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    </div>
    <div class="col-md-6 col-sm-12 float-right">
      <?php echo $this->sortSelector($sortHeadings); ?>
    </div>
  </div>

</div>

<?php $this->trigger('view.browse.before'); ?>

<div id="documents" class="documents-list">
<?php
  $headingTerm = $this->siteSetting('browse_heading_property_term');
  $bodyTerm = $this->siteSetting('browse_body_property_term');
  foreach ($items as $item):
      $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
      $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
  ?>
  <article data-document-id="#" data-document-counter="" itemscope="itemscope" itemtype="http://schema.org/Thing" class="document">
    <header class="documentHeader row">
      <?php if ($itemThumbnail = $this->thumbnail($item, 'medium')): ?>
        <div class="document-thumbnail">
          <?php echo $item->linkRaw($itemThumbnail, null, ['class' => 'img-thumbnail', 'loading' => 'lazy']); ?>
        </div>
      <?php endif; ?>
      <h3 class="index_title document-title-heading">
        <?php echo $item->link($heading, null, ["class" => "foo"]); ?>
      </h3>
      <?php if ($body): ?>
      <div class="description">
        <p>
          <?php echo nl2br($escape($body)); ?>
        </p>
      </div>
      <?php endif; ?>
    </header>
  </article>

<?php endforeach; ?>
</div>

<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
