<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<!-- view/common/block-layout/browse-preview.html -->


<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<div id="documents" class="documents-list mb-3">
  <?php
    $headingTerm = $this->siteSetting('browse_heading_property_term');
    $bodyTerm = $this->siteSetting('browse_body_property_term');
  ?>
  <?php foreach ($this->resources as $resource):?>
    <?php
      $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]')]) : $resource->displayTitle();
      $body = $bodyTerm ? $resource->value($bodyTerm) : $resource->displayDescription();
     ?>
    <article data-document-id="#" data-document-counter="" itemscope="itemscope" itemtype="http://schema.org/Thing" class="document">
      <?php if ($itemThumbnail = $this->thumbnail($resource, 'medium', ['class' => 'img-thumbnail', 'loading' => 'lazy'])): ?>
        <div class="document-thumbnail">
          <?php echo $resource->linkRaw($itemThumbnail); ?>
        </div>
      <?php endif; ?>
      <header class="documentHeader row">
        <h3 class="index_title document-title-heading">
          <?php echo $resource->link($heading); ?>
        </h3>
      </header>

      <?php if ($body): ?>
      <div class="description document-preview row">
        <p>
          <?php echo nl2br($escape($body)); ?>
        </p>
      </div>
      <?php endif; ?>
    </article>

  <?php endforeach; ?>
</div>

<?php
if ($this->linkText):
    echo $this->hyperlink($this->linkText, $this->url(
        'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
    ), ['class' => 'btn btn-primary']);
endif;
?>
