<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/main.css'));
$this->headScript()->prependFile('https://code.jquery.com/jquery-3.5.1.slim.min.js', 'Omeka');
$this->headScript()->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js', 'Omeka');
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }

            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <!-- <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a> -->
        <?php echo $userBar; ?>

        <header class="masthead image-masthead" role="banner">

          <!-- TODO: get from theme-settings -->
          <span class='background-container' style="background-image: url('https://dev.dlmenetwork.org/images/85/132,42,1364,137/1800,180/0/default.jpg')"></span>

          <span class="background-container-gradient"></span>
          <nav class="navbar navbar-expand-md navbar-dark topbar" role="navigation" aria-label="Utilities">
            <div class="container">
              <a href="<?php echo $site->url(); ?>" class="navbar-brand">
                <!-- TODO get from theme-settings -->
                <img class="dlme-logo" alt="" role="presentation" src="https://dlmenetwork.org/assets/logo-e42af4f27e9ed7b2f868b533990ae50bebe01bb57663a1d745bb37cbaa271234.png" />
                Digital Library of the Middle East
              </a>
              <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#user-util-collapse" aria-controls="user-util-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
          </nav>

          <div id="exhibit-navbar" class="exhibit-navbar navbar navbar-light navbar-expand-md" role="navigation" aria-label="Exhibit navigation">
            <div class="container flex-column flex-md-row">

              <ul class="navbar-nav mr-auto">
                <!-- TODO: add .nav-item around li -->
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
              </ul>
              <div class="navbar-right navbar-nav exhibit-search-form mt-3 mt-md-0">
                  <!-- TODO: rewrite this partial for Bootstrap form -->
                  <?php echo $this->partial('common/search-form'); ?>
              </div>
            </div>
          </div>
        </header>

        <main id="main-container" class="container" role="main" aria-label="Main content">
          <div class="row">
              <div class="col-md-12">
                <?php echo $this->content; ?>
              </div>
          </div>
        </main>

        <footer class="footer" role="contentinfo">
          <div class="container">
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
            <?php else: ?>
              <div class="partner-heading">
                <?php echo $this->translate('Powered by the Digital Library of the Middle East'); ?>
              </div>
            <?php endif; ?>
          </div>
        </footer>
    </body>
</html>
