<?php
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink(['rel' => 'preconnect', 'href' => 'https://fonts.googleapis.com']);
$this->headLink(['rel' => 'preconnect', 'href' => 'https://fonts.googleapis.com', 'crossorigin' => '']);
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Markazi+Text');
$this->headLink()->appendStylesheet($this->assetUrl('css/main.css'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
// $this->jsTranslate(); //
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }

            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <!-- <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a> -->
        <?php echo $userBar; ?>

        <header class="masthead image-masthead" role="banner">
          <?php if ($headerContent = $this->themeSettingAssetUrl('header')): ?>
            <span class="background-container" style="background-image: url('<?php echo $headerContent; ?>');"></span>
          <?php else: ?>
            <!-- <span class='background-container' style="background-image: url('https://dev.dlmenetwork.org/images/85/132,42,1364,137/1800,180/0/default.jpg')"></span> -->
            <span class='background-container' style="background-image: url('https://placeimg.com/1800/180/any')"></span>
          <?php endif; ?>

          <span class="background-container-gradient"></span>
          <nav class="navbar navbar-expand-md navbar-dark topbar" role="navigation" aria-label="Utilities">
            <div class="container">
              <a href="<?php echo $site->url(); ?>" class="navbar-brand">
                <?php if ($logoContent = $this->themeSettingAssetUrl('logo')): ?>
                  <img class="dlme-logo" alt="dlme-logo" role="presentation" src="<?php echo $logoContent; ?>" />
                <?php else: ?>
                  <img class="dlme-logo" alt="dlme-logo" role="presentation" src="https://placeimg.com/50/50/any" />
                <?php endif; ?>
                Digital Library of the Middle East
              </a>
              <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#user-util-collapse" aria-controls="user-util-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
          </nav>

          <div id="exhibit-navbar" class="exhibit-navbar navbar navbar-light navbar-expand-md" role="navigation" aria-label="Exhibit navigation">
            <div class="container flex-column flex-md-row">
                <!-- TODO: add .nav-item around li -->
                <?php
                //@see https://github.com/omeka/Omeka/blob/master/application/libraries/Zend/View/Helper/Navigation/Menu.php#L902
                // may need to do this manually as there is not a direct way to decorate <li>
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1,
                    'activeClass' => 'active',
                    'ulClass' => 'navbar-nav mr-auto',
                    'addPageClassToLi' => true
                ]);
                ?>

              <div class="navbar-right navbar-nav exhibit-search-form mt-3 mt-md-0">
                  <?php echo $this->partial('common/search-form'); ?>
              </div>
            </div>
          </div>
        </header>

        <main id="main-container" class="container" role="main" aria-label="Main content">
          <div class="row">
              <div class="col-md-12">
                <?php echo $this->content; ?>
              </div>
          </div>
        </main>

        <footer class="footer" role="contentinfo">
          <div class="container">
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
            <?php else: ?>
              <div class="partner-heading">
                <?php echo $this->translate('Powered by the Digital Library of the Middle East'); ?>
              </div>
            <?php endif; ?>
          </div>
        </footer>
    </body>
</html>
